TESTPFX          := test
TEST_CFLAGS      := -Wall -Wextra -std=c11 -g -I$(PHSCAN_ROOT) -pthread
TEST_PROGRAM     := test-server
TEST_SRCS        := $(TESTPFX)/server.c $(PHSCAN_ROOT)/common.c
TEST_FULLPROGRAM := $(TESTPFX)/$(TEST_PROGRAM)
